AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 3 Factor Cevixe Example - Core

Globals:
  Function:
    Runtime: go1.x
    Timeout: 5
    Handler: handler
    MemorySize: 128
    Environment:
      Variables:
        CVX_GRAPHQL_GATEWAY: !ImportValue GraphqlApiUrl
        CVX_EVENT_BUS: !ImportValue EventBusArn
        CVX_EVENT_STORE: !ImportValue EventStore
        CVX_STATE_STORE: !ImportValue StateStore
        CVX_OBJECT_STORE: !ImportValue ObjectStore

Resources:
  CdcFn:
    Type: "AWS::Serverless::Function"
    Metadata:
      BuildMethod: makefile
    Properties:
      Policies:
        - S3ReadPolicy:
            BucketName: !ImportValue ObjectStore
        - SNSPublishMessagePolicy:
            TopicName: !ImportValue EventBus
        - AWSLambdaDynamoDBExecutionRole
      Environment:
        Variables:
          EventBus: !ImportValue EventBusArn
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream: !ImportValue EventStoreStreamArn
            BatchSize: 1
            StartingPosition: TRIM_HORIZON
  StateFn:
    Type: "AWS::Serverless::Function"
    Metadata:
      BuildMethod: makefile
    Properties:
      Policies:
        - DynamoDBWritePolicy:
            TableName: !ImportValue StateStore
        - S3ReadPolicy:
            BucketName: !ImportValue ObjectStore
        - AWSLambdaDynamoDBExecutionRole
      Environment:
        Variables:
          StateStore: !ImportValue StateStore
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream: !ImportValue EventStoreStreamArn
            BatchSize: 25
            StartingPosition: TRIM_HORIZON
  NotifyFn:
    Type: "AWS::Serverless::Function"
    Metadata:
      BuildMethod: makefile
    Properties:
      Policies:
        - AWSLambdaDynamoDBExecutionRole
        - S3ReadPolicy:
            BucketName: !ImportValue ObjectStore
        - Statement:
          - Sid: AppSyncLambdaClientPolicy
            Effect: Allow
            Action:
              - appsync:GraphQL
            Resource:
              - arn:aws:appsync:*:*:apis/*/*
              - Fn::Join:
                  - ""
                  - - !ImportValue GraphqlApiArn
                    - '/'
                    - '*'
      Environment:
        Variables:
          GraphqlApiUrl: !ImportValue GraphqlApiUrl
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream: !ImportValue EventStoreStreamArn
            BatchSize: 25
            StartingPosition: TRIM_HORIZON
