AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Products Command Service

Parameters:
  ApplicationName:
    Type: String
    MaxLength: 120
    Description: cevixe application name

Globals:
  Function:
    Runtime: go1.x
    Timeout: 5
    Handler: handler
    MemorySize: 128
    Environment:
      Variables:
        CVX_GRAPHQL_API_URL:
          Fn::ImportValue:
            Fn::Join:
              - "-"
              - - !Ref ApplicationName
                - 'GraphqlApiUrl'
        CVX_EVENT_BUS_ARN:
          Fn::ImportValue:
            Fn::Join:
              - "-"
              - - !Ref ApplicationName
                - 'EventBusArn'
        CVX_EVENT_STORE_NAME:
          Fn::ImportValue:
            Fn::Join:
              - "-"
              - - !Ref ApplicationName
                - 'EventStoreName'
        CVX_STATE_STORE_NAME:
          Fn::ImportValue:
            Fn::Join:
              - "-"
              - - !Ref ApplicationName
                - 'StateStoreName'
        CVX_OBJECT_STORE_NAME:
          Fn::ImportValue:
            Fn::Join:
              - "-"
              - - !Ref ApplicationName
                - 'ObjectStoreName'

Resources:
  CreateProductFnQueue:
    Type: AWS::SQS::Queue
  UpdateProductFnQueue:
    Type: AWS::SQS::Queue
  DeleteProductFnQueue:
    Type: AWS::SQS::Queue
  CreateProductFn:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Policies:
        - DynamoDBCrudPolicy:
            TableName:
              Fn::ImportValue:
                Fn::Join:
                  - "-"
                  - - !Ref ApplicationName
                    - 'EventStoreName'
        - S3CrudPolicy:
            BucketName:
              Fn::ImportValue:
                Fn::Join:
                  - "-"
                  - - !Ref ApplicationName
                    - 'ObjectStoreName'
      Events:
        CreateProduct:
          Type: SNS
          Properties:
            Topic:
              Fn::ImportValue:
                Fn::Join:
                  - "-"
                  - - !Ref ApplicationName
                    - 'EventBusArn'
            SqsSubscription:
              BatchSize: 1
              QueueArn: !GetAtt CreateProductFnQueue.Arn
              QueueUrl: !Ref CreateProductFnQueue
            FilterPolicy:
              event_type:
                - CreateProductCreated
  UpdateProductFn:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Policies:
        - DynamoDBCrudPolicy:
            TableName:
              Fn::ImportValue:
                Fn::Join:
                  - "-"
                  - - !Ref ApplicationName
                    - 'EventStoreName'
        - S3CrudPolicy:
            BucketName:
              Fn::ImportValue:
                Fn::Join:
                  - "-"
                  - - !Ref ApplicationName
                    - 'ObjectStoreName'
      Events:
        UpdateProduct:
          Type: SNS
          Properties:
            Topic:
              Fn::ImportValue:
                Fn::Join:
                  - "-"
                  - - !Ref ApplicationName
                    - 'EventBusArn'
            SqsSubscription:
              BatchSize: 1
              QueueArn: !GetAtt UpdateProductFnQueue.Arn
              QueueUrl: !Ref UpdateProductFnQueue
            FilterPolicy:
              event_type:
                - UpdateProductCreated
  DeleteProductFn:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Policies:
        - DynamoDBCrudPolicy:
            TableName:
              Fn::ImportValue:
                Fn::Join:
                  - "-"
                  - - !Ref ApplicationName
                    - 'EventStoreName'
        - S3CrudPolicy:
            BucketName:
              Fn::ImportValue:
                Fn::Join:
                  - "-"
                  - - !Ref ApplicationName
                    - 'ObjectStoreName'
      Events:
        UpdateProduct:
          Type: SNS
          Properties:
            Topic:
              Fn::ImportValue:
                Fn::Join:
                  - "-"
                  - - !Ref ApplicationName
                    - 'EventBusArn'
            SqsSubscription:
              BatchSize: 1
              QueueArn: !GetAtt DeleteProductFnQueue.Arn
              QueueUrl: !Ref DeleteProductFnQueue
            FilterPolicy:
              event_type:
                - DeleteProductCreated