AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 3 Factor Cevixe Example

Parameters:
  ApplicationName:
    Type: String
    MaxLength: 120
    Description: cevixe application name
  SchemaDefinition:
    Type: String
    Description: graphql application schema

Resources:
  ApiModule:
    Type: AWS::Serverless::Application
    Properties:
      Parameters:
        ApplicationName: !Ref ApplicationName
        SchemaDefinition: !Ref SchemaDefinition
      Location: .aws-sam/build/api/template.yaml
  ProductModule:
    Type: AWS::Serverless::Application
    Properties:
      Parameters:
        ApplicationName: !Ref ApplicationName
      Location: .aws-sam/build/services/product/template.yaml
