AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 3 Factor Cevixe Example - Store

Resources:
  EventBus:
    Type: "AWS::SNS::Topic"
    Properties:
      TopicName: EventBus
  EventStore:
    Type: "AWS::DynamoDB::Table"
    Properties:
      BillingMode: PAY_PER_REQUEST
      TableName: EventStore
      AttributeDefinitions:
        - AttributeName: source_key
          AttributeType: S
        - AttributeName: event_id
          AttributeType: N
      KeySchema:
        - AttributeName: source_key
          KeyType: HASH
        - AttributeName: event_id
          KeyType: RANGE
      StreamSpecification:
        StreamViewType: NEW_IMAGE
  StateStore:
    Type: "AWS::DynamoDB::Table"
    Properties:
      BillingMode: PAY_PER_REQUEST
      TableName: StateStore
      AttributeDefinitions:
        - AttributeName: type
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: type
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
  ObjectStore:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: 3factor.examples.cvx

Outputs:
  EventStore:
    Value: !Ref EventStore
    Export:
      Name: EventStore
  EventStoreArn:
    Value: !GetAtt EventStore.Arn
    Export:
      Name: EventStoreArn
  EventStoreStreamArn:
    Value: !GetAtt EventStore.StreamArn
    Export:
      Name: EventStoreStreamArn
  StateStore:
    Value: !Ref StateStore
    Export:
      Name: StateStore
  StateStoreArn:
    Value: !GetAtt StateStore.Arn
    Export:
      Name: StateStoreArn
  ObjectStore:
    Value: !Ref ObjectStore
    Export:
      Name: ObjectStore
  ObjectStoreArn:
    Value: !GetAtt ObjectStore.Arn
    Export:
      Name: ObjectStoreArn
  EventBus:
    Value: !GetAtt EventBus.TopicName
    Export:
      Name: EventBus
  EventBusArn:
    Value: !Ref EventBus
    Export:
      Name: EventBusArn